services:
  planka-bot:
    image: planka-bot         
    build: .
    container_name: planka-bot
    restart: unless-stopped
    env_file: .env
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
